{% set name = "kwargshelper" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kwargshelper-{{ version }}.tar.gz
  sha256: ec82a95e1aaa96097c641acdbb1e3029025f8c594cdd3309f252f27c9bbad845

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - kwhelp
    - kwhelp.helper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Amourspirit/python-kwargshelper
  summary: Manages testing for valid kwargs key, values pairs and assigns class attributes for pairs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Amourspirit
